--1 Revenue Analysis:
-- Calculate the total revenue generated by the e-commerce platform.
SELECT sum(total_amount) AS total_revenue_in_naira FROM orders;
-- Find the revenue generated per product.
SELECT
	oi.product_id, p.product_name,
	SUM(oi.quantity * oi.price) AS total_revenue_by_product_in_naira
FROM
	orders o
JOIN order_items oi ON
	(o.order_id = oi.order_id)
JOIN products p ON
	(p.product_id = oi.product_id)
GROUP BY
	oi.product_id, p.product_name
ORDER BY oi.product_id;

--2 Customer Insights:
-- List the top 5 customers by total spending.
SELECT
	c.customer_id,
	c.name,
	SUM(o.total_amount) AS total_spending_by_customer_in_naira
FROM
	orders o
JOIN customers c ON
	(o.customer_id = c.customer_id)
GROUP BY
	c.customer_id,
	c.name
ORDER BY
	total_spending_by_customer_in_naira DESC
LIMIT 5;


-- Identify customers who haven’t made any purchases.
SELECT
	c.customer_id,
	c.name
FROM
	customers c
LEFT JOIN orders o ON
	(o.customer_id = c.customer_id)
WHERE
	o.order_id IS NULL;

--3 Product Trends:
--Find the top 3 best-selling products.
SELECT
	oi.product_id,
	p.product_name,
	SUM(oi.quantity) AS total_quantity_sold
FROM
	order_items oi
JOIN products p ON
	(oi.product_id = p.product_id)
GROUP BY
	oi.product_id,
	p.product_name
ORDER BY
	total_quantity_sold DESC
LIMIT 3;

--Identify products that are out of stock.
SELECT * FROM products p WHERE stock_quantity = 0;




--4 Order Details:
-- Retrieve all items in a specific order, including product names, quantities, and prices.
SELECT
	o.order_id,
	o.order_date,
	p.product_name,
	oi.quantity,
	oi.price
FROM
	order_items oi
JOIN orders o ON
	(oi.order_id = o.order_id)
JOIN products p ON
	(oi.product_id = p.product_id)
WHERE
	o.order_id = 12;


--Calculate the total amount of an order.


SELECT
	order_id,
	SUM(quantity * price) AS total_amount
FROM
	order_items
GROUP BY
	order_id
HAVING
	order_id = 2;


--5 Monthly Trends:
--Calculate the number of orders and total revenue for each month.
SELECT
	date_trunc('month',	order_date) AS month,
	count(*) AS number_of_orders,
	SUM(total_amount) AS total_revenue_in_naira
FROM
	orders o
GROUP BY
	date_trunc('month',	order_date);


















